-- MySQL Script generated by MySQL Workbench
-- Tue Dec  9 14:39:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Project
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `Project` DEFAULT CHARACTER SET utf8 COLLATE utf8_estonian_ci ;
USE `Project` ;

DROP TABLE IF EXISTS UsersLogs;
DROP TABLE IF EXISTS FileVersions;
DROP TABLE IF EXISTS Files;
DROP TABLE IF EXISTS UsersFolders;
DROP TABLE IF EXISTS Folder;
DROP TABLE IF EXISTS Logs;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Roles;

-- Создаем таблицу Roles
CREATE TABLE IF NOT EXISTS Roles (
  idRoles INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  PRIMARY KEY (idRoles)
) ENGINE = InnoDB;

-- Создаем таблицу Users
CREATE TABLE IF NOT EXISTS Users (
  idUsers INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  password VARCHAR(60) NOT NULL,
  idRoles INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (idUsers),
  UNIQUE INDEX name_UNIQUE (name ASC),
  INDEX fk_Users_Roles_idx (idRoles ASC),
  CONSTRAINT fk_Users_Roles
    FOREIGN KEY (idRoles)
    REFERENCES Roles (idRoles)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Создаем таблицу Logs с новой структурой
CREATE TABLE IF NOT EXISTS Logs (
  idLogs INT NOT NULL AUTO_INCREMENT,
  actionType VARCHAR(100) NOT NULL,
  idUsers INT NULL,
  targetId INT NULL,
  targetType ENUM('user', 'folder', 'file', 'system', 'role', 'log', 'session') NULL,
  status ENUM('success', 'failed', 'warning', 'info') DEFAULT 'info',
  ipAddress VARCHAR(45) NULL,
  userAgent VARCHAR(255) NULL,
  module VARCHAR(50) NULL COMMENT 'Модуль системы (auth, user, file, folder, etc.)',
  details TEXT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (idLogs),
  INDEX idx_logs_user (idUsers),
  INDEX idx_logs_module (module),
  INDEX idx_logs_status (status),
  INDEX idx_logs_createdAt (createdAt DESC),
  CONSTRAINT fk_Logs_Users
    FOREIGN KEY (idUsers)
    REFERENCES Users (idUsers)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB COMMENT = 'Журнал действий системы';

-- Создаем таблицу Folder
CREATE TABLE IF NOT EXISTS Folder (
  idFolder INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(45) NOT NULL,
  parentId INT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (idFolder),
  INDEX fk_Folder_Folder_idx (parentId ASC),
  CONSTRAINT fk_Folder_Folder
    FOREIGN KEY (parentId)
    REFERENCES Folder (idFolder)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Создаем таблицу UsersFolders
CREATE TABLE IF NOT EXISTS UsersFolders (
  idUsers INT NOT NULL,
  idFolders INT NOT NULL,
  permission ENUM('READ', 'WRITE', 'ADMIN') DEFAULT 'READ',
  PRIMARY KEY (idUsers, idFolders),
  INDEX fk_UsersFolders_Users_idx (idUsers ASC) VISIBLE,
  INDEX fk_UsersFolders_Folder_idx (idFolders ASC) VISIBLE,
  CONSTRAINT fk_UsersFolders_Users
    FOREIGN KEY (idUsers)
    REFERENCES Users (idUsers)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_UsersFolders_Folder
    FOREIGN KEY (idFolders)
    REFERENCES Folder (idFolder)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Создаем таблицу Files
CREATE TABLE IF NOT EXISTS Files (
  idFiles INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  idFolders INT NOT NULL,
  fileSize BIGINT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  currentVersionId INT NULL,
  PRIMARY KEY (idFiles),
  INDEX fk_Files_Folder_idx (idFolders ASC) VISIBLE,
  CONSTRAINT fk_Files_Folder
    FOREIGN KEY (idFolders)
    REFERENCES Folder (idFolder)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Создаем таблицу FileVersions
CREATE TABLE IF NOT EXISTS FileVersions (
  idFileVersions INT NOT NULL AUTO_INCREMENT,
  versionNumber INT NOT NULL,
  storageType ENUM('full', 'delta') NOT NULL DEFAULT 'full',
  storagePath VARCHAR(512) NOT NULL,
  baseVersionId INT NULL DEFAULT NULL,
  idFiles INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  checksum VARCHAR(64) NULL,
  PRIMARY KEY (idFileVersions),
  INDEX fk_FileVersions_Files_idx (idFiles ASC) VISIBLE,
  INDEX fk_FileVersions_BaseVersion_idx (baseVersionId ASC) VISIBLE,
  CONSTRAINT fk_FileVersions_Files
    FOREIGN KEY (idFiles)
    REFERENCES Files (idFiles)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_FileVersions_BaseVersion
    FOREIGN KEY (baseVersionId)
    REFERENCES FileVersions (idFileVersions)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Добавляем внешний ключ для currentVersionId после создания FileVersions
ALTER TABLE Files
ADD CONSTRAINT fk_Files_CurrentVersion
  FOREIGN KEY (currentVersionId)
  REFERENCES FileVersions (idFileVersions)
  ON DELETE SET NULL
  ON UPDATE CASCADE;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;