ALTER TABLE FileVersions
ADD COLUMN fileContent LONGBLOB NULL,
ADD COLUMN originalFileName VARCHAR(255) NULL,
ADD COLUMN mimeType VARCHAR(100) NULL,
ADD COLUMN fileSize BIGINT NULL;

ALTER TABLE FileVersions
MODIFY COLUMN storagePath VARCHAR(512) NULL;
